<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<title>Manage Users</title>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" type="text/css" href="/zf/public/ext/resources/css/ext-all.css" />
<script type="text/javascript" src="/zf/public/ext/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/zf/public/ext/ext-all.js"></script>
<script type="text/javascript" src="/zf/public/js/Ext.ux.grid.Search.js"></script>
<script type="text/javascript" src="/zf/public/js/Ext.ux.grid.RowActions.js"></script>
<link rel="stylesheet" type="text/css" href="/zf/public/css/icons.css" />
<link rel="stylesheet" type="text/css" href="/zf/public/themes/x-theme-<?= $this->layout ?>/resources/css/xtheme-<?= $this->layout ?>.css">
<script type="text/javascript" src="/zf/public/users/manager.jsa"></script>
<link rel="stylesheet" type="text/css" href="/zf/public/modules/users/css/default.css" />

</head>
<body>

<div id="dynamicEditorGrid" class="dynamicEditorGrid"></div>

</body>
</html>