<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<title><?= $this->portal ?></title>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="/zf/public/images/favicon.ico" />
<link rel="stylesheet" type="text/css" href="/zf/public/ext/resources/css/ext-all.css" />
<script type="text/javascript" src="/zf/public/ext/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/zf/public/ext/ext-all.js"></script>
  <script type="text/javascript" src="/zf/public/js/miframe.js"></script>
<script type="text/javascript" src="/zf/public/default.jsa"></script>
<link rel="stylesheet" type="text/css" href="/zf/public/css/icons.css" />
<link rel="stylesheet" type="text/css" href="/zf/public/themes/x-theme-<?= $this->layout ?>/resources/css/xtheme-<?= $this->layout ?>.css">

</head>
<body>

<div id="ViewPort"></div>

</body>
</html>